# Generated by Django 4.2.7 on 2023-12-09 12:16

import colorfield.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
            ],
            options={
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(max_length=250)),
                ('flat', models.IntegerField()),
                ('korpus', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Classrooms',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('manual', 'Manual')], default='manual', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_full_name', models.CharField(max_length=255, verbose_name='school_full_name')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Admins', to='main.admin')),
            ],
            options={
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('photo3x4', models.ImageField(blank=True, null=True, upload_to='')),
                ('short_info', models.TextField()),
                ('classl', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='main.class')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='TeacherWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50)])),
                ('classl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.class')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classrooms')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('speciality_university', models.TextField()),
                ('degree', models.CharField(choices=[('Среднее', 'Среднее'), ('Высшее', 'Высшее')], default='Высшее', max_length=20)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name_plural': 'Speciality History',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_name', models.CharField(max_length=355)),
                ('slider_photo', models.CharField(max_length=350)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='schoolPasport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_address', models.CharField(max_length=250)),
                ('tel_phone_school', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=250)),
                ('amount_of_children', models.IntegerField()),
                ('ul_sany', models.IntegerField()),
                ('kiz_sany', models.IntegerField()),
                ('school_lang', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=250)),
                ('vmestimost', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
                ('number_of_classes', models.IntegerField()),
                ('number_of_1_4_students', models.IntegerField()),
                ('number_of_1_4_classes', models.IntegerField()),
                ('number_of_5_9_students', models.IntegerField()),
                ('number_of_5_9_classes', models.IntegerField()),
                ('number_of_10_11_students', models.IntegerField()),
                ('number_of_10_11_classes', models.CharField(max_length=20)),
                ('amount_of_family', models.CharField(max_length=20)),
                ('amount_of_parents', models.CharField(max_length=20)),
                ('pedagog_sheber', models.IntegerField()),
                ('pedagog_moderator', models.IntegerField()),
                ('pedagog_sarapshy', models.IntegerField()),
                ('pedagog_zertteushy', models.IntegerField()),
                ('pedagog', models.IntegerField()),
                ('instagram_account', models.CharField(max_length=250)),
                ('facebook_account', models.CharField(max_length=250)),
                ('youtube_account', models.CharField(max_length=250)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'School Pasport',
            },
        ),
        migrations.CreateModel(
            name='School_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_photo', models.ImageField(upload_to='main/static/img')),
                ('school_full_name', models.CharField(max_length=100)),
                ('established', models.DateField(verbose_name='Established')),
                ('school_directors', models.TextField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'School History',
            },
        ),
        migrations.CreateModel(
            name='School_Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=100)),
                ('director_photo', models.ImageField(upload_to='')),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'School Director',
            },
        ),
        migrations.CreateModel(
            name='School_Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('administator_photo', models.ImageField(upload_to='')),
                ('position', models.CharField(max_length=100)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'School Administration',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Пн', 'Пн'), ('Вт', 'Вт'), ('Ср', 'Ср'), ('Чт', 'Чт'), ('Пт', 'Пт'), ('Сб', 'Сб')], default='Пн', max_length=20)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('plan', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
                ('smena', models.IntegerField(choices=[(1, '1 смена'), (2, '2 смена'), (3, '3 смена'), (4, '4 смена')], default=1)),
                ('classl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.class')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classrooms')),
                ('classroom2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_g2', to='main.classrooms')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
                ('subject2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_g2', to='main.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
                ('teacher2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_g2', to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Pride_of_the_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=150)),
                ('student_success', models.CharField(max_length=150)),
                ('type_of_success', models.CharField(max_length=150)),
                ('classl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.class')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'Pride of the School',
            },
        ),
        migrations.CreateModel(
            name='PhotoforNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/static/img/school_news')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_photos', to='main.news')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='news_photos', to='main.photofornews'),
        ),
        migrations.AddField(
            model_name='news',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='main.school'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=250)),
                ('food_reti', models.CharField(max_length=150)),
                ('food_sostav', models.TextField()),
                ('vihod', models.CharField(max_length=250)),
                ('week_day', models.CharField(choices=[('Пн', 'Пн'), ('Вт', 'Вт'), ('Ср', 'Ср'), ('Чт', 'Чт'), ('Пт', 'Пт'), ('Сб', 'Сб')], default='Пн', max_length=20)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Kruzhok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kruzhok_name', models.CharField(max_length=250)),
                ('photo', models.ImageField(null=True, upload_to='main/static/img')),
                ('purpose', models.CharField(max_length=500)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(max_length=200)),
                ('job_characteristic', models.TextField(default='')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name_plural': 'Job History',
            },
        ),
        migrations.CreateModel(
            name='Facultative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Пн', 'Пн'), ('Вт', 'Вт'), ('Ср', 'Ср'), ('Чт', 'Чт'), ('Пт', 'Пт'), ('Сб', 'Сб')], default='Пн', max_length=20)),
                ('faculative_name', models.CharField(max_length=200)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('classl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.class')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classrooms')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Extra_Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_short_name', models.CharField(max_length=100)),
                ('type_full_name', models.CharField(max_length=200)),
                ('type_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Выберите цвет')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'Extra Lessons',
            },
        ),
        migrations.AddField(
            model_name='classrooms',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='main.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classrooms'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
        ),
        migrations.AddField(
            model_name='admin',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Пн', 'Пн'), ('Вт', 'Вт'), ('Ср', 'Ср'), ('Чт', 'Чт'), ('Пт', 'Пт'), ('Сб', 'Сб')], default='Пн', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lesson_order', models.PositiveIntegerField(default=1)),
                ('kruzhok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.kruzhok')),
            ],
            options={
                'unique_together': {('kruzhok', 'week_day', 'start_time', 'end_time', 'lesson_order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='admin',
            unique_together={('school',)},
        ),
    ]
