# Generated by Django 4.2.7 on 2023-12-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='end_date',
            field=models.DateField(),
        ),
    ]
