# Generated by Django 4.2.7 on 2023-12-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_eng_name',
            field=models.CharField(max_length=255, null=True, verbose_name='school_full_name'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_ru_name',
            field=models.CharField(max_length=255, null=True, verbose_name='school_full_name'),
        ),
    ]
