# Generated by Django 4.2.7 on 2023-12-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_jobhistory_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='end_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='job_characteristic',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='start_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='specialityhistory',
            name='end_date',
            field=models.CharField(max_length=10),
        ),
    ]
