# Generated by Django 4.2.7 on 2023-12-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_altynbelgi_redcertificate_school_socialmedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
