# Generated by Django 4.2.7 on 2023-12-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_school_school_eng_name_school_school_ru_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpasport',
            name='established',
            field=models.IntegerField(default=2008),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='amount_of_children',
            field=models.IntegerField(null=True),
        ),
    ]
