# Generated by Django 4.2.7 on 2023-12-11 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slider_slider_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pride_of_the_School',
            new_name='Oner_Success',
        ),
        migrations.AlterModelOptions(
            name='altynbelgi',
            options={'verbose_name_plural': 'AltynBelgi'},
        ),
        migrations.AlterModelOptions(
            name='oner_success',
            options={'verbose_name_plural': 'Pride of the School Oner'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='end_time',
        ),
        migrations.CreateModel(
            name='Sport_Success',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=150)),
                ('student_success', models.CharField(max_length=250)),
                ('classl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.class')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'Pride of the School Sport',
            },
        ),
        migrations.CreateModel(
            name='PandikOlimpiada_Success',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=150)),
                ('student_success', models.CharField(max_length=250)),
                ('classl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.class')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'Pride of the School Olimpiada',
            },
        ),
    ]
