# Generated by Django 4.2.7 on 2023-12-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_schoolpasport_established_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_full_name',
            new_name='school_kz_name',
        ),
    ]
