# Generated by Django 4.2.7 on 2023-12-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_pride_of_the_school_oner_success_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altynbelgi',
            name='classl',
        ),
        migrations.RemoveField(
            model_name='redcertificate',
            name='classl',
        ),
        migrations.RemoveField(
            model_name='school_socialmedia',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='school_socialmedia',
            name='school_website',
        ),
        migrations.RemoveField(
            model_name='school_socialmedia',
            name='youtube_account',
        ),
        migrations.AddField(
            model_name='school_socialmedia',
            name='type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('website', 'Manual')], default='website', max_length=10),
        ),
        migrations.AlterField(
            model_name='altynbelgi',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='oner_success',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='oner_success',
            name='student_success',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pandikolimpiada_success',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='pandikolimpiada_success',
            name='student_success',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='redcertificate',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='sport_success',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='sport_success',
            name='student_success',
            field=models.TextField(),
        ),
    ]
