# Generated by Django 4.2.7 on 2023-12-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_altynbelgi_classl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_socialmedia',
            old_name='instagram_account',
            new_name='account_name',
        ),
        migrations.AlterField(
            model_name='school_socialmedia',
            name='type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('website', 'website')], default='website', max_length=10),
        ),
    ]
