# Generated by Django 4.2.7 on 2023-12-11 10:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_instagram_account_school_socialmedia_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_lessons',
            name='type_short_name',
        ),
        migrations.RemoveField(
            model_name='facultative',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='facultative',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='smena',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classl',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='short_info',
        ),
        migrations.AddField(
            model_name='class',
            name='language',
            field=models.CharField(choices=[('KZ', 'KZ'), ('RU', 'RU')], default='KZ', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='timezone',
            field=models.CharField(choices=[('GMT+5', 'GMT+5'), ('GMT+6', 'GMT+6')], default='GMT+5', max_length=20),
        ),
        migrations.AddField(
            model_name='specialityhistory',
            name='mamandygy',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], default='EASY', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pedagog',
            field=models.CharField(choices=[('Pedagog Sheber', 'Pedagog Sheber'), ('Pedagog  Zertteushy', 'Pedagog  Zertteushy'), ('Pedagog Sarapshy', 'Pedagog Sarapshy'), ('Pedagog Moderator', 'Pedagog Moderator'), ('Pedagog', 'Pedagog'), ('Pedagog  Stazher', 'Pedagog  Stazher'), ('Pedagog  Zhogary', 'Pedagog  Zhogary'), ('Pedagog  1 sanat', 'Pedagog  1 sanat'), ('Pedagog  2 sanat', 'Pedagog  2 sanat'), ('Pedagog sanat zhok', 'Pedagog sanat zhok')], default='Pedagog Sheber', max_length=20),
        ),
        migrations.AlterField(
            model_name='facultative',
            name='week_day',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week_day',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='week_day',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week_day',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
                ('smena', models.IntegerField(choices=[(1, '1 смена'), (2, '2 смена'), (3, '3 смена'), (4, '4 смена')], default=1)),
                ('number', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)])),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
        ),
        migrations.AddField(
            model_name='facultative',
            name='ring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ring'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ring'),
        ),
    ]
