# Generated by Django 4.2.7 on 2023-12-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_extra_lessons_type_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
