# Generated by Django 4.2.7 on 2023-12-11 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='DopUrok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=20)),
                ('faculative_name', models.CharField(max_length=200)),
                ('classl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.class')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classrooms')),
                ('ring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ring')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
                ('typez', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.extra_lessons')),
            ],
        ),
        migrations.CreateModel(
            name='DopUrokRing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
                ('smena', models.IntegerField(choices=[(1, '1 смена'), (2, '2 смена'), (3, '3 смена'), (4, '4 смена')], default=1)),
                ('number', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)])),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='typez',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.extra_lessons'),
        ),
        migrations.DeleteModel(
            name='Facultative',
        ),
    ]
